# This workflow to test whether the runner is able to build a podman
# container image with Z where quay image is used 
# Issue: https://github.com/IBM/actionspz/issues/63
name: quay-pull-test

on:
  workflow_dispatch:

jobs:
  mtu-test:
    runs-on: ubuntu-24.04-s390x
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Build podman image
        run: |
          whoami
          podman build \
            -f Dockerfile
            -t my-image \
            .
